apiVersion: v1
kind: Service
metadata:
  labels:
    app: us-ordertracker
  name: us-ordertracker
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
    targetPort: 8030
  selector:
    app: us-ordertracker
status:
  loadBalancer: {}
