ALTER TABLE order_tracker MODIFY order_status_date datetime NULL;
ALTER TABLE order_tracker MODIFY scheduled_start_date datetime NULL;
ALTER TABLE order_tracker MODIFY scheduled_end_date datetime NULL;
ALTER TABLE order_tracker DROP COLUMN source;

delete from application_parameter where code='ADMINISTRATOR_REPORTING_DAYS';
delete from application_parameter where code='BREAK_TIME';
delete from application_parameter where code='COORDINATOR_REPORTING_DAYS';
delete from application_parameter where code='DRUGSTORE_CALL_CENTER';
delete from application_parameter where code='ENABLE_GROUPING_ALGORITHM';
delete from application_parameter where code='ETA_COLOR_GREEN';
delete from application_parameter where code='ETA_COLOR_ORANGE';
delete from application_parameter where code='ETA_COLOR_RED';
delete from application_parameter where code='ETA_CONDITION_GREEN';
delete from application_parameter where code='ETA_CONDITION_ORANGE';
delete from application_parameter where code='ETA_CONDITION_RED';
delete from application_parameter where code='LOG_FIRE_AVAILABLE_ACTIVITY';
delete from application_parameter where code='LOG_FIRE_AVAILABLE_STATUS';
delete from application_parameter where code='LOG_FIRE_ENVIRONMENT';
delete from application_parameter where code='LOG_FIRE_INTEGRATION_ACTIVE';
delete from application_parameter where code='LOG_FIRE_INTEGRATION_LOG';
delete from application_parameter where code='LOG_FIRE_NORMAL_ORDER_PRIORITY';
delete from application_parameter where code='LOG_FIRE_NORMAL_ORDER_TYPE';
delete from application_parameter where code='LOG_FIRE_ORDER_ORIGIN';
delete from application_parameter where code='LOG_FIRE_ORDER_PACKING_ACTIVITY_CODE';
delete from application_parameter where code='LOG_FIRE_ORDER_REQUEST';
delete from application_parameter where code='LOG_FIRE_ORDER_STATUS_ACTIVITY_CODE';
delete from application_parameter where code='LOG_FIRE_ORDER_TYPE';
delete from application_parameter where code='LOG_FIRE_OUTFLOW';
delete from application_parameter where code='LOG_FIRE_SALE_CONFIRMED';
delete from application_parameter where code='LOG_FIRE_SALE_REJECTED';
delete from application_parameter where code='LOG_FIRE_SCHEDULED_ORDER_PRIORITY';
delete from application_parameter where code='LOG_FIRE_SCHEDULED_ORDER_TYPE';
delete from application_parameter where code='LOG_FIRE_SYNC_SETTING';
delete from application_parameter where code='LOG_FIRE_VERSION';
delete from application_parameter where code='MARK_ARRIVE_VALIDATED';
delete from application_parameter where code='MAX_INKAVENTA_ATTEMPT_QUANTITY';
delete from application_parameter where code='MAX_MINUTES_IN_GROUP_BUFFER';
delete from application_parameter where code='MAX_ORDERS_BY_GROUP';
delete from application_parameter where code='MAX_ORDERS_BY_REGROUP';
delete from application_parameter where code='MAX_RETRY_HOOK_CONSUMER';
delete from application_parameter where code='MAX_TIME_DISPATCHED_STATUS';
delete from application_parameter where code='MAX_TIME_PICKING_STATUS';
delete from application_parameter where code='MAX_TIME_PREPARED_STATUS';
delete from application_parameter where code='METERS_GROUP_RADIUS';
delete from application_parameter where code='MOTORIZED_CANNOT_BREAK';
delete from application_parameter where code='ORDERS_WITH_ERROR';
delete from application_parameter where code='ORDER_EXECUTE_FETCH';
delete from application_parameter where code='ORDER_LAST_EVALUATED_DATE';
delete from application_parameter where code='ORDER_LAST_EVALUATED_DATE_OFFSET';
delete from application_parameter where code='ORDER_LAST_EVALUATED_ID';
delete from application_parameter where code='ORDER_SEARCH_MAX_OLD_DAYS';
delete from application_parameter where code='PERFORMANCE_DISPATCHED_LAST_MINUTES';
delete from application_parameter where code='PERFORMANCE_META_ASIGNADA';
delete from application_parameter where code='PERFORMANCE_META_DESPACHO';
delete from application_parameter where code='PERFORMANCE_META_ORDENES';
delete from application_parameter where code='PERFORMANCE_ORDERS_LAST_MINUTES';
delete from application_parameter where code='PERFORMANCE_TOTAL_LAST_MINUTES';
delete from application_parameter where code='PERFORMANCE_UMBRAL_DAY';
delete from application_parameter where code='PERFORMANCE_UMBRAL_HOUR';
delete from application_parameter where code='PICKER_SCAN_COMMAND';
delete from application_parameter where code='PICKER_SCAN_TRAY';
delete from application_parameter where code='PROFIT_REPORT_DAYS';
delete from application_parameter where code='PROFIT_REPORT_TITLE';
delete from application_parameter where code='RETRY_HOOK_CONSUMER_REQUEST';
delete from application_parameter where code='ROUTE_BUFFER';
delete from application_parameter where code='START_TIME_PERIOD_IN_MOTORIZED';

delete from status where type='TRACKING' and code='ASSIGNED';
delete from status where type='TRACKING' and code='IN_BREAK';

