apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-ordertracker
  labels:
    app: us-ordertracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us-ordertracker
  template:
    metadata:
      labels:
        app: us-ordertracker
    spec:
      containers:
      - name: us-ordertracker
        image: 519901771307.dkr.ecr.us-west-2.amazonaws.com/ordertracker-service:{{TAG}}
        env:
        - name: environment
          value: "qa2"
        - name: LOG_LEVEL_SYSTEM
          value: "INFO"
        - name: LOG_LEVEL_BUSINESS
          value: "ERROR"
        - name: LOGS_FOLDER
          value: "/var/log/us-ordertracker"
        ports:
        - containerPort: 8030
        resources:
          limits:
            cpu: 1000m
            memory: 800Mi
          requests:
            cpu: 100m
            memory: 500Mi
      restartPolicy: Always
